### ISSUE TITLE
Problem z core.py

### ISSUE THREAD

**Issue by akarcinski** [agh-bit-academy/SummerProject2022#83]
Podczas pisania chciałem sprawdzić zadanie 17 skoro są już wszystkie pliki. Zrobiłem wcześniej na wszelki wypadek pull --rebase. Po uruchomieniu core.py dostałem następujący komunikat:

PS F:\summer_project\SummerProject2022> python core.py
Checking Zadanie_01 from Zestaw_1
Checking Zadanie_15 from Zestaw_1
Checking Zadanie_17 from Zestaw_1
Traceback (most recent call last):
  File "F:\summer_project\SummerProject2022\core.py", line 155, in <module>
    while menu(): pass
  File "F:\summer_project\SummerProject2022\core.py", line 147, in menu
    run_all_tests()
  File "F:\summer_project\SummerProject2022\core.py", line 139, in run_all_tests
    run_unit_test(data_source, test_source)
  File "F:\summer_project\SummerProject2022\core.py", line 73, in run_unit_test
    temp_data.append([float(data[i]), int(data[i + n]), data[i + (2 * n)]])
IndexError: list index out of range

Nie wiem czy jest to błąd z mojej strony czy jednak coś z core.py jest nie tak, wolę jednak wrzucić to do Issues.

**Comment by NiEkOKsU** [comment]
Pytest działa poprawnie tutaj więc to chyba coś po stronie core.py

**Comment by Rusiek** [comment]
Tak, jeżeli pytest działa poprawnie to problem leży po stronie core.py. Dostałem już jedno zgłoszenie o podobnym problemie, natomiast nie znam przyczyny tego problem. Obejście omówimy na spotkaniu w piątek. Póki co problem niech zostanie otwarty

**Comment by Kasl0** [comment]
Mam podobny problem. Trochę inny Traceback:

Traceback (most recent call last):
  File "C:\Users\Kaslo\Desktop\GitHub\SummerProject2022\core.py", line 155, in <module>
    while menu(): pass
  File "C:\Users\Kaslo\Desktop\GitHub\SummerProject2022\core.py", line 147, in menu
    run_all_tests()
  File "C:\Users\Kaslo\Desktop\GitHub\SummerProject2022\core.py", line 139, in run_all_tests
    run_unit_test(data_source, test_source)
  File "C:\Users\Kaslo\Desktop\GitHub\SummerProject2022\core.py", line 69, in run_unit_test
    n = int(data[0])
IndexError: list index out of range

**Comment by Rusiek** [comment]
Trzeba wpisać cokolwiek w puste pola
